//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MidProjectEntities : DbContext
    {
        public MidProjectEntities()
            : base("name=MidProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCurrency> tCurrencies { get; set; }
        public virtual DbSet<tCustomer> tCustomers { get; set; }
        public virtual DbSet<tNewProduct> tNewProducts { get; set; }
        public virtual DbSet<tOrderDetail> tOrderDetails { get; set; }
        public virtual DbSet<tOrderPlatform> tOrderPlatforms { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tPaymentMethod> tPaymentMethods { get; set; }
        public virtual DbSet<tPicture> tPictures { get; set; }
        public virtual DbSet<tproduct> tproducts { get; set; }
        public virtual DbSet<tProductStatu> tProductStatus { get; set; }
        public virtual DbSet<tProductType> tProductTypes { get; set; }
        public virtual DbSet<tPurchasingOrder> tPurchasingOrders { get; set; }
        public virtual DbSet<tPurchasingOrderDetail> tPurchasingOrderDetails { get; set; }
        public virtual DbSet<tStock> tStocks { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
    }
}
