//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingItem
    {
        public int PendingPK { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Contents { get; set; }
        public bool CheckBox { get; set; }
    }
}
