//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNewProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNewProduct()
        {
            this.tOrderDetails = new HashSet<tOrderDetail>();
            this.tPurchasingOrderDetails = new HashSet<tPurchasingOrderDetail>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Color { get; set; }
        public int Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> ReoderLevel { get; set; }
        public byte[] Image { get; set; }
    
        public virtual tNewProduct tNewProduct1 { get; set; }
        public virtual tNewProduct tNewProduct2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchasingOrderDetail> tPurchasingOrderDetails { get; set; }
    }
}
