//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> BidFee { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual tCustomer tCustomer { get; set; }
        public virtual tOrderPlatform tOrderPlatform { get; set; }
    }
}
