//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPaymentMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPaymentMethod()
        {
            this.tPurchasingOrders = new HashSet<tPurchasingOrder>();
        }
    
        public int PaymentMethodID { get; set; }
        public string PaymentMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchasingOrder> tPurchasingOrders { get; set; }
    }
}
