//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPurchasingOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPurchasingOrderDetail()
        {
            this.tStocks = new HashSet<tStock>();
        }
    
        public int PurchasingOrderDetailID { get; set; }
        public Nullable<int> PurchasingOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> ArrivedQuantity { get; set; }
        public Nullable<int> ReimburseQuantity { get; set; }
    
        public virtual tNewProduct tNewProduct { get; set; }
        public virtual tPurchasingOrder tPurchasingOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStock> tStocks { get; set; }
    }
}
