//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPurchasingOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPurchasingOrder()
        {
            this.tPurchasingOrderDetails = new HashSet<tPurchasingOrderDetail>();
        }
    
        public int PurchasingOrderID { get; set; }
        public Nullable<System.DateTime> PurchasingDate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> ImportDuty { get; set; }
        public Nullable<decimal> tariff { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        public virtual tCurrency tCurrency { get; set; }
        public virtual tPaymentMethod tPaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchasingOrderDetail> tPurchasingOrderDetails { get; set; }
    }
}
