//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mist126_27
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStock
    {
        public int StockID { get; set; }
        public Nullable<int> ProductDetailID { get; set; }
        public Nullable<int> PurchasingOrderDetailID { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> ReoderLevel { get; set; }
    
        public virtual tPurchasingOrderDetail tPurchasingOrderDetail { get; set; }
    }
}
